- set_fact: bid_price_string="{{ ',BidPrice={{ emr_spot_instance_bid_price }}' if emr_use_spot_instances else '' }}"

- name: Ensure tmp dir
  file:
    path: "{{ playbook_dir }}/tmp"
    state: directory

- name: Create configurations.json file
  template:
    src: configurations.json.j2
    dest: "{{ playbook_dir }}/tmp/configurations.json"

- name: Create EMR Cluster
  shell: "{{ lookup('template', '{{ playbook_dir }}/roles/aws-emr-cluster/templates/create-cluster-command.j2') }}"

- name: Remove tmp dir
  file:
    path: "{{ playbook_dir }}/tmp"
    state: absent
