- name: Create KMS Key Policy
  debug: msg="{{ lookup('template', 'roles/aws-kms-master-key/templates/policy.json.j2', convert_data=False) }}"
  vars:
    key_admin_arns:
      - "arn:aws:iam::{{ account_id }}:role/EMR_DefaultRole"
      - "arn:aws:iam::{{ account_id }}:role/EMR_EC2_DefaultRole"
    key_admin_arn_string: "{{ key_admin_arns|wrap|join(', ') }}"

- name: Create KMS Key
  when: kms_create_key == 'True'
  shell: >
    aws kms create-key
    --policy {{ lookup('template', 'roles/aws-kms-master-key/templates/policy.json.j2', convert_data=False) }}
    --description {{ kms_key_description }}
    --key-usage ENCRYPT_DECRYPT
  register: kms_create_key_response


- name: Output Key Creation Response
  debug: var=kms_create_key_response
