- name: Create EMR Cluster
  hosts: localhost
  vars_files:
    - vars/user.yml
  environment:
    AWS_PROFILE: "{{ aws_boto_profile }}"
    AWS_REGION: "{{ aws_region }}"

  roles:
  #  - { role: aws-kms-master-key, when: kms_create_key }
  #  - { role: aws-s3-bucket, when: s3_create_bucket }
    - { role: prepare-emr-config }
    - { role: aws-emr-cluster }
